# https://github.com/bitnami/charts/tree/master/bitnami/kafka

replicaCount: 2
defaultReplicationFactor: 2 
numPartitions: 2
service:
    type: LoadBalancer
    loadBalancerIP: 10.0.19.1
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true" 
externalAccess:
    enabled: true
    service:
        type: LoadBalancer
        # keep total IPs same as number of replicas
        loadBalancerIPs:
            - 10.0.19.10
            - 10.0.19.11            
        annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
