apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-demo-shop 
  name: shipment-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: shipment-service
  type: ClusterIP
status:
  loadBalancer: {}
