apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-demo-shop
  name: shop
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: shop
  type: ClusterIP
status:
  loadBalancer: {}
