apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-demo-shop
  name: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shop
    spec:
      containers:
        - image: surenmcode/shop
          name: shop          
status: {}
