apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
spec:
  replicas: 2

---
apiVersion: v1
kind: Service
metadata:  
  name: shop
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
