apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: py-orders
    demo: dapr-grpc
  name: py-orders
  namespace: py-orders-dapr-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-orders
      demo: dapr-grpc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: py-orders
        demo: dapr-grpc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "py-orders-dapr-grpc"        
        dapr.io/app-protocol: "grpc"
        dapr.io/grpc-port: "3500"  
    spec:
      containers:
      - image: surenmcode/py-orders:1.1-dapr-grpc
        name: py-orders
        imagePullPolicy: Always
        resources: {}
status: {}
